services:
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - ${MYSQL_DOCKER_DIR:-./docker/mysql_db}/${PROJECT_NAME}:/var/data
    networks:
      - scoped-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: docker/pma
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_pma
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASS}
      PMA_PMADB: ${PMA_PMADB}
    volumes:
      - ./docker/pma/config.inc.5.1.1.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - scoped-network

  fixtures:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_fixtures
    working_dir: /data
    volumes:
      - ./shell/:/data/
      - ./.env:/data/.env
    entrypoint: >
      bash -c "      
      /bin/bash fixtures.sh > log.log 2>&1    
      "
    networks:
      - scoped-network
    restart: "no"

  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
    container_name: ${PROJECT_NAME}_node
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
      fixtures:
        condition: service_completed_successfully
    healthcheck:
      # there is no CURL in alpine image, but we have node for sure
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:${NODE_PORT}/api/healthcheck', { signal: AbortSignal.timeout(1000) }).then(res => process.exit(res.ok ? 0 : 1)).catch(() => process.exit(1));\""]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - scoped-network

networks:
  scoped-network:
    name: network-${PROJECT_NAME}
